# docker-compose.yaml

services:
  ###########################
  # OpenSearch
  ###########################
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
      - 9600:9600

  ###########################
  # OpenSearch Dashboards
  ###########################
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true

  ###########################
  # Prometheus
  ###########################
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.external-url=http://prometheus.admin.achenar.net
      - --web.enable-lifecycle
    ports:
      - 9090:9090
    expose:
      - "9090"
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./etc/prometheus.alerts.yaml:/etc/prometheus/prometheus.alerts.yaml:ro

  ###########################
  # Alertmanager
  ###########################
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    ports:
      - 9093:9093
    expose:
      - "9093"
    volumes:
      - ./etc/alertmanager.yaml:/etc/alertmanager/alertmanager.yml:ro

  ###########################
  # Alertmanager2opensearch
  ###########################
  alertmanager2opensearch:
    # build: ../
    image: ghcr.io/kuoss/alertmanager2opensearch
    container_name: alertmanager2opensearch
    command:
      - --opensearch.address=http://opensearch:9200
    ports:
      - 9097:9097
    expose:
      - "9097"
    volumes:
      - ./etc/alertmanager.yaml:/etc/alertmanager/alertmanager.yml:ro
